export const DIFFICULTIES = {
  easy: {
    id: 'easy',
    name: 'Tranquilo',
    label: 'Fácil',
    croquetas: 120,
    catArrivalRate: 45000,
    needDecay: 0.022,
    incomeMultiplier: 1.3,
    description: 'Más croquetas, gatos llegan despacio y necesidades bajan con calma.',
  },
  normal: {
    id: 'normal',
    name: 'Equilibrado',
    label: 'Normal',
    croquetas: 80,
    catArrivalRate: 35000,
    needDecay: 0.036,
    incomeMultiplier: 1.0,
    description: 'Experiencia balanceada; las necesidades aparecen un poco antes.',
  },
  hard: {
    id: 'hard',
    name: 'Salvaje',
    label: 'Difícil',
    croquetas: 50,
    catArrivalRate: 25000,
    needDecay: 0.055,
    incomeMultiplier: 0.75,
    description: 'Pocos recursos, gatos exigentes y necesidades que llegan pronto.',
  },
};

export const NEEDS = ['food', 'sleep', 'fun', 'health', 'warmth', 'hygiene'];

export const NEED_LABELS = {
  food: '🍽 Alimento',
  sleep: '🛏 Descanso',
  fun: '🎾 Entretención',
  health: '💊 Salud',
  warmth: '🌡 Temperatura',
  hygiene: '🧹 Higiene',
};

export const TILE_BASE_COST = 8;
export const TILE_COST_INCREMENT = 3;

export const CAT_NAMES = [
  'Michi', 'Luna', 'Simba', 'Nala', 'Whiskers', 'Mittens', 'Shadow', 'Ginger',
  'Oreo', 'Pixel', 'Mochi', 'Tofu', 'Cleo', 'Felix', 'Bella', 'Max',
  'Chloe', 'Oliver', 'Lily', 'Leo', 'Mia', 'Charlie', 'Sophie', 'Jack',
  'Zoe', 'Tiger', 'Coco', 'Milo', 'Daisy', 'Oscar', 'Penny', 'Smokey',
  'Pepper', 'Boots', 'Patches', 'Snowball', 'Midnight', 'Pumpkin', 'Marble',
  'Socks', 'Bandit', 'Princess', 'Dusty', 'Honey', 'Ash', 'Pearl', 'Rusty',
];

export const BUILDING_CATEGORIES = [
  { id: 'terrain', label: 'Terreno' },
  { id: 'food', label: 'Alimentación' },
  { id: 'sleep', label: 'Descanso' },
  { id: 'fun', label: 'Entretención' },
  { id: 'health', label: 'Salud' },
  { id: 'warmth', label: 'Temperatura' },
  { id: 'hygiene', label: 'Higiene' },
  { id: 'decoration', label: 'Decoración' },
];

export const BUILDINGS = {
  hex_tile: {
    id: 'hex_tile',
    name: 'Casilla',
    icon: '⬡',
    category: 'terrain',
    cost: 0,
    description: 'Expande el catio con una nueva casilla hexagonal. El precio sube levemente por cada casilla que ya tengas.',
    provides: {},
    color: '#7ab870',
    height: 0.15,
  },
  food_bowl: {
    id: 'food_bowl',
    name: 'Plato',
    icon: '🍽',
    category: 'food',
    cost: 12,
    description: 'Plato de croquetas. Cubre la necesidad de alimento de 1 gato cercano.',
    provides: { food: 1 },
    color: '#e8a878',
    height: 0.25,
  },
  water_fountain: {
    id: 'water_fountain',
    name: 'Bebedero',
    icon: '💧',
    category: 'health',
    cost: 18,
    description: 'Agua fresca constante. Mejora la salud de los gatos en casillas adyacentes.',
    provides: { health: 1 },
    color: '#7ab8d8',
    height: 0.35,
  },
  bed: {
    id: 'bed',
    name: 'Cama',
    icon: '🛏',
    category: 'sleep',
    cost: 15,
    description: 'Cama acogedora para 1 gato. Aumenta el límite de gatos en +1.',
    provides: { sleep: 1 },
    catCapacity: 1,
    color: '#c8a0c0',
    height: 0.3,
  },
  double_bed: {
    id: 'double_bed',
    name: 'Cama doble',
    icon: '🛋',
    category: 'sleep',
    cost: 28,
    description: 'Cama amplia para 2 gatos que pueden dormir juntos. Aumenta el límite en +2.',
    provides: { sleep: 2 },
    catCapacity: 2,
    color: '#b890b8',
    height: 0.35,
  },
  scratcher: {
    id: 'scratcher',
    name: 'Rascador',
    icon: '🪵',
    category: 'fun',
    cost: 14,
    description: 'Poste rascador. Satisface la entretención y mantiene las uñas sanas.',
    provides: { fun: 1, health: 0.3 },
    color: '#d0a878',
    height: 0.55,
  },
  toy_ball: {
    id: 'toy_ball',
    name: 'Pelota',
    icon: '⚽',
    category: 'fun',
    cost: 8,
    description: 'Juguete simple. Entretención básica para gatos curiosos.',
    provides: { fun: 0.6 },
    color: '#f08080',
    height: 0.15,
  },
  litter_box: {
    id: 'litter_box',
    name: 'Arenero',
    icon: '🪣',
    category: 'hygiene',
    cost: 16,
    description: 'Arenero limpio. Esencial para la higiene; sin areneros la felicidad cae rápido.',
    provides: { hygiene: 1 },
    color: '#b0b8c0',
    height: 0.2,
  },
  lamp: {
    id: 'lamp',
    name: 'Lámpara',
    icon: '💡',
    category: 'warmth',
    cost: 20,
    description: 'Calor suave para noches frías. Cubre temperatura en casillas cercanas.',
    provides: { warmth: 1 },
    color: '#f0d070',
    height: 0.45,
    upgradeable: true,
    maxLevel: 3,
    upgradeCosts: [15, 25],
    upgradeBonus: { warmth: 0.5 },
  },
  catnip_plant: {
    id: 'catnip_plant',
    name: 'Planta gatera',
    icon: '🌿',
    category: 'fun',
    cost: 22,
    description: 'Hierba gatera aromática. Entretención y felicidad extra en el área.',
    provides: { fun: 1.2 },
    color: '#78c078',
    height: 0.35,
    upgradeable: true,
    maxLevel: 3,
    upgradeCosts: [18, 30],
    upgradeBonus: { fun: 0.4 },
  },
  garden: {
    id: 'garden',
    name: 'Jardín',
    icon: '🌸',
    category: 'decoration',
    cost: 25,
    description: 'Pequeño jardín florido. Mejora entretención y temperatura del entorno.',
    provides: { fun: 0.5, warmth: 0.3 },
    color: '#88c878',
    height: 0.4,
    upgradeable: true,
    maxLevel: 3,
    upgradeCosts: [20, 35],
    upgradeBonus: { fun: 0.3, warmth: 0.2 },
  },
  shelter: {
    id: 'shelter',
    name: 'Refugio',
    icon: '🏠',
    category: 'warmth',
    cost: 30,
    description: 'Casa cubierta contra lluvia y viento. Protección térmica para varios gatos.',
    provides: { warmth: 1.5, sleep: 0.5 },
    catCapacity: 1,
    color: '#d09070',
    height: 0.6,
  },
  tree: {
    id: 'tree',
    name: 'Árbol',
    icon: '🌳',
    category: 'decoration',
    cost: 20,
    description: 'Sombra natural y ambiente agradable. Refresca en días calurosos.',
    provides: { warmth: 0.5, fun: 0.3 },
    color: '#68a868',
    height: 0.7,
  },
};

export const BASE_CAT_LIMIT = 2;
export const HEX_RANGE = 4;

export const HAPPINESS_WARNING_THRESHOLD = 35;
export const AUTO_SAVE_INTERVAL = 15000;
